export { OdontogramaSVG } from "./OdontogramaSVG";
export type { ToothData, ToothStatus, ToothFace } from "./OdontogramaSVG";
export { TreatmentPlanCard, TreatmentPlanFunnel } from "./TreatmentPlanCard";
export type { TreatmentPlan, PlanItem, Installment, FunnelData } from "./TreatmentPlanCard";
export { AnamneseWizard } from "./AnamneseWizard";
export type { AnamneseData } from "./AnamneseWizard";
export { ProntuarioTimeline } from "./ProntuarioTimeline";
export type { TimelineEntry, TimelineEntryType } from "./ProntuarioTimeline";
export { AgendaDental } from "./AgendaDental";
export type { DentalAppointment } from "./AgendaDental";
export { ClinicalImages } from "./ClinicalImages";
export type { ClinicalImage } from "./ClinicalImages";
