import { StyleSheet, Platform } from "react-native";
import { Colors } from "@/constants/colors";

export const m = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)", justifyContent: "center", alignItems: "center", padding: 16 },
  // Item 3 (16/06): maxWidth 480 -> 700 para acomodar melhor o volume de info.
  // width "100%" mantem mobile full-bleed; maxWidth so morde no desktop.
  sheet: { backgroundColor: Colors.bg2, borderRadius: 20, width: "100%", maxWidth: 700, maxHeight: "90%", overflow: "hidden", borderWidth: 1, borderColor: Colors.border },

  head: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 16, borderBottomWidth: 1, borderBottomColor: Colors.border },
  crumb: { flexDirection: "row", alignItems: "center", gap: 5 },
  crumbTxt: { fontSize: 13, fontWeight: "700", color: Colors.violet3 },
  xBtn: { width: 30, height: 30, borderRadius: 9, backgroundColor: Colors.bg3, alignItems: "center", justifyContent: "center" },

  body: { flexGrow: 0 },

  fixedHeader: { paddingHorizontal: 18, paddingTop: 12, backgroundColor: Colors.bg2, borderBottomWidth: 1, borderBottomColor: Colors.border },
  fixedMeta: { flexDirection: "row", gap: 8, marginBottom: 12 },
  fixedMetaItem: { flex: 1, backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 },
  fixedMetaLbl: { fontSize: 8.5, fontWeight: "800", letterSpacing: 0.6, color: Colors.ink3 },
  fixedMetaVal: { fontSize: 14, fontWeight: "800", color: Colors.ink, marginTop: 3 },

  tabs: { flexDirection: "row", gap: 6, marginBottom: 14 },
  tab: { flex: 1, alignItems: "center", paddingVertical: 8, borderRadius: 9, backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border },
  tabOn: { backgroundColor: Colors.violet, borderColor: Colors.violet2 },
  tabTxt: { fontSize: 11, fontWeight: "700", color: Colors.ink2 },
  tabTxtOn: { color: "#fff" },

  scoreBanner: { flexDirection: "row", alignItems: "flex-start", gap: 9, backgroundColor: Colors.amber + "18", borderWidth: 1, borderColor: Colors.amber + "44", borderRadius: 11, padding: 12, marginBottom: 13 },
  scoreBannerTxt: { flex: 1, fontSize: 12, color: Colors.amber, lineHeight: 17 },
  scorePill: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  scorePillTxt: { fontSize: 10, fontWeight: "700" },

  cust: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 16 },
  custL: { flexDirection: "row", alignItems: "center", gap: 12 },
  avatar: { width: 48, height: 48, borderRadius: 14, backgroundColor: Colors.violetD, borderWidth: 1, borderColor: Colors.border2, alignItems: "center", justifyContent: "center" },
  avatarTxt: { fontSize: 18, fontWeight: "700", color: Colors.violet3 },
  custName: { fontSize: 18, fontWeight: "700", color: Colors.ink },
  custSub: { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 3 },
  dot: { width: 7, height: 7, borderRadius: 4 },
  pill: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  pillTxt: { fontSize: 10, fontWeight: "700" },
  waBtn: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: "rgba(52,211,153,0.12)", borderWidth: 1, borderColor: "rgba(52,211,153,0.4)", borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9 },
  waTxt: { fontSize: 12, fontWeight: "700", color: Colors.green },

  card: { backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border, borderRadius: 14, padding: 14, marginBottom: 13 },

  heroCard: { backgroundColor: Colors.violetD, borderWidth: 1, borderColor: Colors.border2, borderRadius: 16, padding: 18, marginBottom: 13, alignItems: "center" },
  heroLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1.5, color: Colors.violet3, textTransform: "uppercase", marginBottom: 6 },
  heroValue: { fontSize: 34, fontWeight: "800", marginBottom: 4 },
  heroSub: { fontSize: 12, color: Colors.ink3, textAlign: "center" },

  cardTitleRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  cardTitle: { fontSize: 10, fontWeight: "800", letterSpacing: 1, color: Colors.ink3, textTransform: "uppercase" },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 11 },
  rowK: { fontSize: 13, fontWeight: "600", color: Colors.ink },
  rowKsub: { fontSize: 11, color: Colors.ink3, marginTop: 1 },
  rowV: { fontSize: 17, fontWeight: "800" },

  newAccBtn: { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: Colors.violetD, borderWidth: 1, borderColor: Colors.border2, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5 },
  newAccTxt: { fontSize: 11, fontWeight: "700", color: Colors.violet3 },
  newAccRow: { flexDirection: "row", gap: 8, marginBottom: 10 },
  newAccInput: { flex: 1, borderWidth: 1, borderColor: Colors.border2, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 8, color: Colors.ink, fontSize: 13, backgroundColor: Colors.bg2 },
  newAccConfirm: { backgroundColor: Colors.violet, borderRadius: 9, paddingHorizontal: 14, paddingVertical: 8, alignItems: "center", justifyContent: "center" },
  newAccConfirmTxt: { fontSize: 12, fontWeight: "700", color: "#fff" },

  accCard: { borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 12, marginTop: 4, paddingBottom: 4 },
  accTop: { flexDirection: "row", alignItems: "flex-start", gap: 10 },
  accName: { fontSize: 13, fontWeight: "700", color: Colors.ink },
  accMeta: { flexDirection: "row", gap: 6, flexWrap: "wrap", marginTop: 5 },
  accBadge: { paddingHorizontal: 7, paddingVertical: 2, borderRadius: 5, borderWidth: 1 },
  accBadgeTxt: { fontSize: 10, fontWeight: "700" },
  accBalance: { fontSize: 16, fontWeight: "800" },
  accNextDue: { fontSize: 10, color: Colors.ink3, marginTop: 2 },
  accActions: { flexDirection: "row", gap: 8, marginTop: 10, flexWrap: "wrap" },
  accActionBtn: { backgroundColor: Colors.violet, borderRadius: 8, paddingHorizontal: 13, paddingVertical: 7 },
  accActionWa: { backgroundColor: "rgba(52,211,153,0.12)", borderWidth: 1, borderColor: "rgba(52,211,153,0.35)" },
  accActionTxt: { fontSize: 12, fontWeight: "700", color: "#fff" },
  accInstList: { marginTop: 10, borderTopWidth: 1, borderTopColor: Colors.border },

  parc: { flexDirection: "row", alignItems: "flex-start", gap: 10, paddingVertical: 11, borderTopWidth: 1, borderTopColor: Colors.border },
  parcT: { fontSize: 13, fontWeight: "700", color: Colors.ink },
  parcS: { fontSize: 11, color: Colors.ink3, marginTop: 2 },
  badge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1 },
  badgeTxt: { fontSize: 10, fontWeight: "700" },
  receberBtn: { backgroundColor: Colors.violet, borderRadius: 9, paddingHorizontal: 14, paddingVertical: 8 },
  receberTxt: { fontSize: 12, fontWeight: "700", color: "#fff" },

  chargesBreakdown: { marginTop: 7, backgroundColor: Colors.bg2, borderRadius: 9, padding: 9, borderWidth: 1, borderColor: Colors.border2 },
  chargesRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 4 },
  chargesLbl: { fontSize: 11, color: Colors.ink3, flex: 1 },
  chargesVal: { fontSize: 11, fontWeight: "700", color: Colors.ink },
  chargesDaysChip: { fontSize: 10, color: Colors.amber, fontWeight: "700" },
  chargesTotalRow: { borderTopWidth: 1, borderTopColor: Colors.border2, paddingTop: 5, marginTop: 2, marginBottom: 0 },
  chargesTotalLbl: { fontSize: 12, fontWeight: "700", color: Colors.ink, flex: 1 },
  chargesTotalVal: { fontSize: 13, fontWeight: "800", color: Colors.red },

  chargesSummary: { marginTop: 12, paddingTop: 11, borderTopWidth: 1, borderTopColor: Colors.border2 },
  chargesSummaryRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 5 },
  chargesSummaryLbl: { fontSize: 12, color: Colors.ink3 },
  chargesSummaryVal: { fontSize: 13, fontWeight: "800", color: Colors.ink },

  freeBox: { backgroundColor: Colors.violetD, borderWidth: 1, borderColor: Colors.border2, borderRadius: 14, padding: 14, marginBottom: 13 },
  freeTitle: { fontSize: 10, fontWeight: "800", letterSpacing: 1, color: Colors.violet3, textTransform: "uppercase", marginBottom: 10 },
  modeRow: { flexDirection: "row", gap: 7, marginBottom: 10 },
  modeChip: { flex: 1, alignItems: "center", backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border, borderRadius: 9, paddingVertical: 8 },
  modeChipOn: { backgroundColor: Colors.violet, borderColor: Colors.violet2 },
  modeChipTxt: { fontSize: 11, fontWeight: "700", color: Colors.ink2, textAlign: "center" },
  modeChipTxtOn: { color: "#fff" },
  fieldBlock: { marginTop: 4 },
  fieldLabel: { fontSize: 11, fontWeight: "700", color: Colors.ink3, letterSpacing: 0.4, textTransform: "uppercase", marginBottom: 6 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 10 },
  chip: { backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border, borderRadius: 8, paddingHorizontal: 11, paddingVertical: 6 },
  chipOn: { backgroundColor: Colors.violet, borderColor: Colors.violet2 },
  chipTxt: { fontSize: 11, fontWeight: "700", color: Colors.ink2 },
  chipTxtOn: { color: "#fff" },
  distRow: { flexDirection: "row", alignItems: "center", gap: 10, marginBottom: 8 },
  distLabel: { flex: 1, fontSize: 12, fontWeight: "600", color: Colors.ink },
  distInput: { flexDirection: "row", alignItems: "center", gap: 6, backgroundColor: Colors.bg2, borderWidth: 1, borderColor: Colors.border2, borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7 },
  distField: { width: 80, color: Colors.ink, fontSize: 13, fontWeight: "700", paddingVertical: 0 },
  distTotal: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.border2 },
  distTotalLbl: { fontSize: 12, color: Colors.ink3 },
  distTotalVal: { fontSize: 14, fontWeight: "800", color: Colors.amber },
  amountIn: { flexDirection: "row", alignItems: "center", gap: 8, backgroundColor: Colors.bg2, borderWidth: 1.5, borderColor: Colors.violet2, borderRadius: 11, paddingHorizontal: 14, paddingVertical: 11 },
  amountPrefix: { fontSize: 14, color: Colors.ink3, fontWeight: "600" },
  amountInput: { flex: 1, color: Colors.ink, fontSize: 20, fontWeight: "800", paddingVertical: 0 },
  quickRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 },
  qChip: { backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border, borderRadius: 8, paddingHorizontal: 11, paddingVertical: 6 },
  qChipTxt: { fontSize: 11, fontWeight: "700", color: Colors.ink2 },
  dateInput: { backgroundColor: Colors.bg2, borderColor: Colors.violet2, borderWidth: 1.5, borderRadius: 11, paddingHorizontal: 14, paddingVertical: 11, fontSize: 15, color: Colors.ink },
  dateHint: { fontSize: 11, color: Colors.ink3, marginTop: 6 },
  methods: { flexDirection: "row", gap: 7 },
  method: { flex: 1, alignItems: "center", backgroundColor: Colors.bg3, borderWidth: 1, borderColor: Colors.border, borderRadius: 9, paddingVertical: 9 },
  methodActive: { backgroundColor: Colors.violet, borderColor: Colors.violet2 },
  methodTxt: { fontSize: 12, fontWeight: "700", color: Colors.ink2 },
  after: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 12, paddingTop: 11, borderTopWidth: 1, borderTopColor: Colors.border2 },
  afterK: { fontSize: 12, color: Colors.ink3 },
  afterV: { fontSize: 14, fontWeight: "800", color: Colors.amber },

  tlItem: { flexDirection: "row", gap: 11, paddingVertical: 8, borderTopWidth: 1, borderTopColor: Colors.border },
  tlDot: { width: 10, height: 10, borderRadius: 5, marginTop: 4 },
  tlLine: { flexDirection: "row", alignItems: "baseline", justifyContent: "space-between", gap: 8 },
  tlMain: { fontSize: 13, fontWeight: "600", color: Colors.ink },
  tlAmt: { fontSize: 13, fontWeight: "800" },
  tlSub: { fontSize: 11, color: Colors.ink3, marginTop: 1 },
  tlAccTag: { backgroundColor: Colors.violetD, borderWidth: 1, borderColor: Colors.border2, borderRadius: 5, paddingHorizontal: 6, paddingVertical: 1 },
  tlAccTagTxt: { fontSize: 10, fontWeight: "700", color: Colors.violet3 },
  emptyTxt: { fontSize: 12, color: Colors.ink3, paddingVertical: 6 },

  termsHint: { fontSize: 12, color: Colors.ink3, lineHeight: 17, marginBottom: 10 },
  termsEffRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: Colors.bg2, borderRadius: 9, padding: 10, borderWidth: 1, borderColor: Colors.border2 },
  termsEffLbl: { fontSize: 12, color: Colors.ink3 },
  termsEffVal: { fontSize: 13, fontWeight: "700", color: Colors.violet3 },
  termsInput: { borderWidth: 1, borderColor: Colors.border2, borderRadius: 10, paddingHorizontal: 13, paddingVertical: 11, fontSize: 14, color: Colors.ink, backgroundColor: Colors.bg2 },

  blockRow: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 12, borderTopWidth: 1, borderTopColor: Colors.border },
  blockLabel: { fontSize: 14, fontWeight: "700", color: Colors.ink },
  blockReason: { fontSize: 12, color: Colors.ink3, marginTop: 2 },

  footer: { padding: 16, borderTopWidth: 1, borderTopColor: Colors.border },
  cta: { backgroundColor: Colors.violet, borderRadius: 12, paddingVertical: 14, alignItems: "center" },
  ctaTxt: { fontSize: 14, fontWeight: "700", color: "#fff" },

  calBtn: {
    backgroundColor: Colors.violetD, borderRadius: 8,
    paddingHorizontal: 8, paddingVertical: 6,
    minWidth: 30, alignItems: "center", justifyContent: "center",
    borderWidth: 1, borderColor: Colors.violet + "44",
  },
  editDueDateSheet: {
    borderTopWidth: 1, borderTopColor: Colors.border,
    padding: 16, backgroundColor: Colors.bg3,
  },
  editDueDateHeader: {
    flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 6,
  },
  editDueDateTitle: { fontSize: 14, fontWeight: "800", color: Colors.ink },
  editDueDateSub: { fontSize: 11, color: Colors.ink3, marginBottom: 10, lineHeight: 16 },

  tabSm: { paddingVertical: 5 },

  pixBtn: { backgroundColor: Colors.green + "22", borderRadius: 9, paddingHorizontal: 10, paddingVertical: 7, borderWidth: 1, borderColor: Colors.green + "44" },
  pixBtnTxt: { fontSize: 11, fontWeight: "700", color: Colors.green },

  pixOverlay: { borderTopWidth: 1, borderTopColor: Colors.border, padding: 16, backgroundColor: Colors.bg2 },
  pixOverlayHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 10 },
  pixAmtLabel: { fontSize: 24, fontWeight: "800", color: Colors.ink, textAlign: "center", marginBottom: 2 },
  pixInstLabel: { fontSize: 12, color: Colors.ink3, textAlign: "center", marginBottom: 12 },
  pixEmvBox: { backgroundColor: Colors.bg3, borderRadius: 9, padding: 10, borderWidth: 1, borderColor: Colors.border2, marginTop: 4 },
  pixEmvTxt: { fontSize: 11, color: Colors.ink3, fontFamily: Platform.OS === "web" ? "monospace" : undefined },

  previewBox: { backgroundColor: Colors.bg2, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: Colors.border2, marginTop: 14 },
  previewTitle: { fontSize: 10, fontWeight: "800", letterSpacing: 1, color: Colors.violet3, textTransform: "uppercase", marginBottom: 8 },
  previewRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 6 },
  previewLbl: { fontSize: 12, color: Colors.ink3, flex: 1 },
  previewVal: { fontSize: 12, fontWeight: "700", color: Colors.ink, textAlign: "right" },

  // ── Item 2 (16/06): renegociacao de parcelas ──────────────────────────
  // Botao "Renegociar" (acao secundaria, estilo outline violeta).
  renegActionBtn: { backgroundColor: Colors.violetD, borderWidth: 1, borderColor: Colors.border2 },
  renegActionTxt: { color: Colors.violet3 },
  // Stepper de numero de parcelas (− valor +).
  renegStepRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  renegStepBtn: { width: 40, height: 40, borderRadius: 10, backgroundColor: Colors.bg2, borderWidth: 1, borderColor: Colors.border2, alignItems: "center", justifyContent: "center" },
  renegStepBtnDisabled: { opacity: 0.4 },
  renegStepVal: { minWidth: 56, textAlign: "center", fontSize: 18, fontWeight: "800", color: Colors.ink },
  renegHint: { fontSize: 11, color: Colors.ink3, marginTop: 6, lineHeight: 16 },
  // Linha de delta (desconto/acrescimo) no resumo.
  renegDeltaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 8, paddingTop: 10, borderTopWidth: 1, borderTopColor: Colors.border2 },
  renegDeltaLbl: { fontSize: 12, color: Colors.ink3 },
  renegDeltaVal: { fontSize: 14, fontWeight: "800" },

} as any);
